---
title: "IGVF CRISPR Jamboree 2024: Perturb-seq Inference (Python)"
author: "Gene Katsevich"
date: "February 9, 2024"
output: 
  bookdown::pdf_document2:
    toc: false
urlcolor: blue
---

# Overview

## Perturb-seq inference

The goal of perturb-seq inference is to quantify the extent to which the perturbation of a given genomic element impacts the expression of a given gene. We allow a range of statistical interpretations of this task. In a frequentist framework, this task can be viewed as testing the null hypothesis that the perturbation of the genomic element has no effect on the gene's expression, or as estimating the effect size of the perturbation on the gene's expression. In a Bayesian framework, this task can be viewed as estimating the posterior probability of the presence of a non-zero effect, or as a posterior mean of the effect size. 

## Jamboree goals

The goal of the perturb-seq inference portion of the Jamboree is to implement a number of perturb-seq inference methodologies using common input and output formats. Following the Jamboree, these implementations will be added as modules to a Nextflow pipeline, which will then be used to benchmark their statistical and computational performance. This benchmarking effort will suggest best practices for perturb-seq inference, and will be used to inform the development of the IGVF perturb-seq analysis pipeline.

## Data format overview

The primary input to a perturb-seq inference module is a `MuData` object, which contains both the perturb-seq data and a set of element-gene pairs for which the inference is to be performed. The output of each method should be the same `MuData` object, except with an additional table containing one or more measures of association for each element-gene pair. The `MuData` format is an HDF5-based language-agnostic format compatible with import into both R and Python. Each `MuData` object will contain a minimal set of fields required for inference, and potentially one or more optional fields that provide additional information. For the purposes of this Jamboree, we have provided `MuData` objects for subsets of the Gasperini et al (2019) and Papalexi et al (2021) datasets. For each dataset, we have provided a minimal `MuData` object that contains just the required fields, as well as a more fleshed out object that contains additional optional fields.

## Requested function API, documentation, and demonstration

Please write a function in your language of choice with the following arguments: 

- The first argument should be `mudata_input_fp`, a filepath to a `MuData` object.
- The second argument should be `mudata_output_fp`, a filepath to an output `MuData` object.
- There may be one or more additional arguments specific to your method. 

The function should read the `MuData` object from `mudata_input_fp`, perform the inference, and write the resulting `MuData` object to `mudata_output_fp` (in Python, via `mudata.read_h5mu()`). The function should include documentation of any additional arguments used. Furthermore, please include a demonstration of the use of your function on at least one of the sample datasets provided, and a brief discussion of the results.

# `MuData` format

Let us walk through the input and output format specifications, from the perspective of Python, using a subset of the Gasperini et al (2019) dataset as an example.

```{python, warning = FALSE}
import mudata as md
import pandas as pd
pd.set_option('display.max_columns', None)
```

## Required input fields

We start with an example of the minimal `MuData` object required for perturb-seq inference.

```{python, warning = FALSE}
mudata_input_fp = "data/gasperini_inference_input_minimal.h5mu"
input_minimal = md.read_h5mu(mudata_input_fp)
input_minimal
```
The minimal `MuData` object for perturb-seq inference contains two modalities: `gene` and `guide`. 

### `gene` modality

The `gene` modality just needs to have a `.X` matrix containing the RNA UMI counts. 

```{python}
input_minimal['gene'].X
input_minimal['gene'][:2,:2].to_df()
```
### `guide` modality

The `guide` modality needs to have a `.X` matrix containing the gRNA UMI counts, as well as a `.layers['guide_assignment']` matrix containing the binary gRNA assignments. 

```{python}
input_minimal['guide'].X
input_minimal['guide'].layers['guide_assignment']
```

We can view a couple rows and columns of each:
```{python}
cell_ids = [
    "GCTTGAATCGAATGCT-1_1B_1_SI-GA-F2",
    "GGTGAAGCACCAGGCT-1_1A_6_SI-GA-E7"
]
grna_ids = [
  "GCCCTGCTACCCACTTACAG",
  "ATGTAGAAGGAGACACCGGG"
]
pd.DataFrame(input_minimal['guide'][cell_ids, grna_ids].X.toarray(), 
             index = cell_ids, 
             columns = grna_ids)

pd.DataFrame(input_minimal['guide'][cell_ids, grna_ids].layers['guide_assignment'].toarray(), 
             index = cell_ids, 
             columns = grna_ids)
```

In addition to the guide UMI counts and assignments, the `guide` modality must contain certain metadata information. This includes a `.var` data frame containing at least the binary variable `targeting` (`TRUE` if the guide targets a genomic element of interest or `FALSE` if it is safe- or non-targeting) and the string `intended_target_name` (the name of the genomic element targeted by the guide). 
```{python, warning = FALSE}
input_minimal['guide'].var.iloc[[0, 1, 20, 21, 30, 31]]
```
Note that the `targeting` column is a string rather than a Boolean due to type compatibility issues involving R, Python, and HDF5. It can be cast to a Boolean if desired. 

Finally, the guide modality must contain `uns` fields called `moi` (`low` or `high`) and `capture_method` (`"CROP-seq"` or `"direct capture"`):
```{python, warning = FALSE}
input_minimal['guide'].uns['capture_method'][0]
input_minimal['guide'].uns['moi'][0]
```

### Global `.uns`

The input `MuData` object is also required to have a global `.uns` field named `pairs_to_test`, which is a data frame containing the pairs of elements (specified via `intended_target_name`) and genes (specified via `gene_id`) for which the inference is to be performed.
```{python, warning = FALSE}
pd.DataFrame(input_minimal.uns['pairs_to_test'])
```

## Optional input fields

Next we consider optional fields that can be included in the input `MuData` object.

```{python, warning = FALSE}
mudata_input_fp = "data/gasperini_inference_input.h5mu"
input_optional = md.read_h5mu(mudata_input_fp)
input_optional
```
### `gene` modality

The `MuData` object may include cellwise covariates for the `gene` modality in `.mod['gene].obs`, such as number of genes with nonzero UMI counts (`num_expressed_genes`) and total RNA UMIs (`total_gene_umis`):
```{python, warning = FALSE}
input_optional['gene'].obs
```

The `MuData` object may include per-gene metadata in `.mod['gene'].var`, such as the HGNC gene symbol (`symbol`), the gene chromosome (`chr`), start (`gene_start`), and end (`gene_end`) coordinates:
```{python, warning = FALSE}
input_optional['gene'].var
```

### `guide` modality

The `MuData` object may include cellwise covariates for the `guide` modality in `.mod['guide'].obs`, such as number of guides with nonzero UMI counts (`num_expressed_guides`) and total guide UMIs (`total_guide_umis`):
```{python, warning = FALSE}
input_optional['guide'].obs
```

The `MuData` object may include per-guide metadata in `.mod['guide'].var` in addition to the required `targeting` and `intended_target_name` fields, such as the chromosome (`intended_target_chr`), start (`intended_target_start`), and end (`intended_target_end`) of the targeted element:
```{python, warning = FALSE}
input_optional['guide'].var.iloc[[0, 1, 20, 21, 30, 31]]
```

### Global `.obs`

Optionally, the `MuData` input object can contain a global `obs` field containing cell-level information that is not specific to modality, such as batch information. Here is what it looks like for the Gasperini data:
```{python, warning = FALSE}
input_optional.obs[['prep_batch', 'within_batch_chip', 'within_chip_lane']]
```

### Pairs to test 

Optionally, `.uns['pairs_to_test']` can have a third column: `pair_type`: 
```{python}
pd.DataFrame(input_optional.uns['pairs_to_test'])
```
This optional column classifies pairs based on whether they are intended to be positive controls (an association is known to exist), negative controls (an association is known not to exist), or discovery pairs (pairs where it is unknown whether an association exists). This information need not be used by the inference module, but it is useful for downstream analysis.

## Output fields

The output should be the same `MuData` object as the input, with the addition of a `test_results` field to the global `.uns`:
```{python, warning = FALSE}
mudata_output_fp = "data/gasperini_inference_output.h5mu"
output_optional = md.read_h5mu(mudata_output_fp)
output_optional
```

```{python, warning = FALSE}
pd.DataFrame(output_optional.uns['test_results'])
```
This is a data frame containing the same columns as the `pairs_to_test` data frame, plus at least one column containing a measure of the association for each pair. These columns can be `p_value`, `log2_fc`, `posterior_probability`, or any other measure of association.

# Sample submission

Here we present a sample Jamboree submission.

## Function

Here is a sample function that computes a $p$-value based on a Wilcoxon test:


## Demonstration

Here is a demonstration of this function on the Gasperini data: