---
title: "IGVF CRISPR Jamboree 2024: MuData Proposal"
author: "Gene Katsevich"
date: "January 29, 2024"
output: 
  bookdown::pdf_document2:
    toc: false
urlcolor: blue
---

The goal of this document is to propose a `MuData` object structure for the IGVF CRISPR Jamboree 2024. It builds off of Lucas's [sample Gasperini `MuData` object](https://github.com/IGVF-CRISPR/Pipeline_Gasperini_2019/tree/main) and the [per-guide metadata format](https://docs.google.com/document/d/1tib4To6XjMYTxeBRCgvgRD5JCq2XsmcJDjMcL2AGzso/edit). I will propose variants of the `MuData` structure that are appropriate as inputs and outputs for the gRNA assignment and inference modules. These structures will be exemplified by a subset of the Gasperini data, distinct from Lucas's. For each module, I will present minimal examples of `MuData` objects containing required fields, as well as more fleshed out examples containing optional fields. All of the `MuData` objects are available [on GitHub](https://github.com/Katsevich-Lab/sceptre-igvf/tree/main/data).

```{python, warning = FALSE}
import mudata as md
import pandas as pd
pd.set_option('display.max_columns', None)
```

# gRNA assignment

## gRNA assignment (required fields)

### Input
```{python, warning = FALSE}
guide_assignment_input = md.read_h5mu("data/gasperini_guide_assignment_input_minimal.h5mu")
guide_assignment_input
```
The minimal input `MuData` object for gRNA assignment contains two modalities: `gene` and `guide`. The `gene` modality just needs to have a `.X` matrix containing the gene RNA UMI counts. The `guide` modality needs to have a `.X` matrix containing the gRNA UMI counts, as well as a `.var` data frame containing at least the Boolean variable `targeting` and the string `intended_target_name`:
```{python, warning = FALSE}
guide_assignment_input['guide'].var.iloc[[0, 1, 20, 21, 30, 31]]
```
Note that the `targeting` column is a string rather than a Boolean due to type compatibility issues involving R, Python, and HDF5. It can be cast to a Boolean if desired. Finally, the gRNA assignment input `MuData` object must contain an `uns` field called `moi` (`low` or `high`).

### Output

```{python, warning = FALSE}
guide_assignment_output = md.read_h5mu("data/gasperini_guide_assignment_output_minimal.h5mu")
guide_assignment_output
```
The minimal gRNA assignment output `MuData` object is the same as the input object, except it now has a `.layer` called `guide_assignment`, which is a binary assignment matrix of guides to cells.

## gRNA assignment (optional fields)

### Input

```{python, warning = FALSE}
guide_assignment_input = md.read_h5mu("data/gasperini_guide_assignment_input.h5mu")
guide_assignment_input
```

Optionally, the gRNA assignment input object can contain a top-level `obs` field containing cell-level information that is not specific to modality, such as batch information. Here is what it looks like for the Gasperini data:
```{python, warning = FALSE}
guide_assignment_input.obs[['prep_batch', 'within_batch_chip', 'within_chip_lane']]
```
The gRNA assignment input object may also include cellwise covariates for the `gene` modality, such as number of expressed genes and total RNA UMIs:
```{python, warning = FALSE}
guide_assignment_input['gene'].obs
```
Next, the gRNA assignment input object may contain additional information about the genes:
```{python, warning = FALSE}
guide_assignment_input['gene'].var
```
Finally, the gRNA assignment input object may contain cellwise covariates for the `guide` modality and additional information about the guides beyond the two required fields `targeting` and `intended_target_name`:
```{python, warning = FALSE}
guide_assignment_input['guide'].obs
guide_assignment_input['guide'].var.iloc[[0, 1, 20, 21, 30, 31]]
```

# Inference

## Inference (required fields)

### Input

Here is an example of a `MuData` object containing the minimal required fields for input to the inference module:
```{python, warning = FALSE}
inference_input = md.read_h5mu("data/gasperini_inference_input_minimal.h5mu")
inference_input
```
This is the same as the minimal set of required fields for the output of the gRNA assignment module, except there is an extra field in `uns` called `pairs_to_test`:
```{python, warning = FALSE}
pd.DataFrame(inference_input.uns['pairs_to_test'])
```
The minimal required fields in `pairs_to_test` are `gene_id` and `intended_target_name`. Each row specifies a test to be conducted between CRISPR perturbation of a given target and the the expression of a given gene. 

### Output

```{python, warning = FALSE}
inference_output = md.read_h5mu("data/gasperini_inference_output_minimal.h5mu")
inference_output
```
The minimal required fields in the output of the inference module are the same as the minimal required fields for the input, except there is an extra field in `uns` called `test_results`:
```{python, warning = FALSE}
pd.DataFrame(inference_output.uns['test_results'])
```
This is a data frame containing the same columns as the `pairs_to_test` data frame, plus at least one column containing a measure of the association for each pair. These columns can be `p_value`, `log2_FC`, `posterior_probability`, or any other measure of association. We just have to standardize these column names.

## Inference (optional fields)

### Input

Here is an example of a `MuData` object containing some optional fields for input to the inference module:
```{python, warning = FALSE}
inference_input = md.read_h5mu("data/gasperini_inference_input.h5mu")
inference_input
```

The additional fields are the same as those described for the gRNA assignment module. The only additional optional field is in the `pairs_to_test` data frame:
```{python}
pd.DataFrame(inference_input.uns['pairs_to_test'])
```
Note the third column: `pair_type`. This optional column classifies pairs based on whether they are intended to be positive controls (an association is known to exist), negative controls (an association is known not to exist), or discovery pairs (pairs where it is unknown whether an association exists). This information need not be used by the inference module, but it is useful for downstream analysis.

### Output

Here is an example of a `MuData` object containing some optional fields for output from the inference module:
```{python, warning = FALSE}
inference_output = md.read_h5mu("data/gasperini_inference_output.h5mu")
inference_output
```

The only difference from before is in `test_results`:
```{python, warning = FALSE}
pd.DataFrame(inference_output.uns['test_results'])
```
Now, the output includes the optional `pair_type` as well as a `log2_fc` in addition to the `p_value` column. This illustrates how an inference method may output multiple measures of association for each pair.